import { pgTable, uuid, text, integer, numeric, boolean, bigint, timestamp, index } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';

export const calls = pgTable('calls', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  freeswitchUuid: text('freeswitch_uuid').unique(),
  campaignId: uuid('campaign_id'),
  leadId: uuid('lead_id'),
  agentId: uuid('agent_id'),
  didId: uuid('did_id'),
  byocCarrierId: uuid('byoc_carrier_id'),
  direction: text('direction').notNull(),
  callerId: text('caller_id').notNull(),
  callerName: text('caller_name'),
  calleeNumber: text('callee_number').notNull(),
  calleeName: text('callee_name'),
  status: text('status').notNull().default('ringing'),
  disposition: text('disposition'),
  hangupCause: text('hangup_cause'),
  amdResult: text('amd_result'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  answeredAt: timestamp('answered_at', { withTimezone: true }),
  endedAt: timestamp('ended_at', { withTimezone: true }),
  durationSeconds: integer('duration_seconds'),
  talkTimeSeconds: integer('talk_time_seconds'),
  holdTimeSeconds: integer('hold_time_seconds').default(0),
  waitTimeSeconds: integer('wait_time_seconds').default(0),
  wrapTimeSeconds: integer('wrap_time_seconds').default(0),
  recordingUrl: text('recording_url'),
  recordingSizeBytes: bigint('recording_size_bytes', { mode: 'number' }),
  cost: numeric('cost', { precision: 10, scale: 6 }),
  ratePerMinute: numeric('rate_per_minute', { precision: 10, scale: 6 }),
  billingSeconds: integer('billing_seconds'),
  hasTranscript: boolean('has_transcript').default(false),
  hasSummary: boolean('has_summary').default(false),
  fraudFlagged: boolean('fraud_flagged').default(false),
  mos: numeric('mos', { precision: 4, scale: 2 }),
  jitterMs: numeric('jitter_ms', { precision: 8, scale: 2 }),
  packetLossPct: numeric('packet_loss_pct', { precision: 5, scale: 2 }),
  carrier: text('carrier'),
  carrierIp: text('carrier_ip'),
  codec: text('codec'),
  userAgent: text('user_agent'),
  sipFromUri: text('sip_from_uri'),
  sipToUri: text('sip_to_uri'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_calls_tenant').on(table.tenantId, table.startedAt),
  index('idx_calls_agent').on(table.agentId, table.startedAt),
  index('idx_calls_campaign').on(table.campaignId),
  index('idx_calls_uuid').on(table.freeswitchUuid),
  index('idx_calls_status').on(table.status),
  index('idx_calls_caller').on(table.callerId),
  index('idx_calls_callee').on(table.calleeNumber),
]);
