#!/bin/bash
# Kamailio role bootstrap — applies the canonical sip_proxy config to a new
# fleet sip_proxy node. Idempotent. Run from ctl02 over SSH.
#
# Usage:  kamailio-bootstrap.sh <sip-node-public-ip> <floating-ip>
#
# What it does:
#   1. Write the canonical kamailio.cfg with REGISTRAR + DISPATCHER, FIP advertise,
#      pike anti-flood module loaded.
#   2. Generate dispatcher.list pointing at the active freeswitch fleet (port 5080
#      — the external profile, no auth, ACL-gated by source IP).
#   3. Restart kamailio.
#
# When the FS fleet changes, re-run this script per sip_proxy node so the
# dispatcher list stays current. (A control-plane watcher could automate this.)

set -euo pipefail

SIP_IP="${1:-}"
FIP="${2:-}"
[ -z "$SIP_IP" ] || [ -z "$FIP" ] && { echo "usage: $0 <sip-node-ip> <floating-ip>"; exit 1; }

[ -f /opt/tpbx/.env ] && set -a && . /opt/tpbx/.env && set +a
SSH_KEY="${SSH_PRIVATE_KEY_PATH:-/opt/tpbx/secrets/ssh_key}"
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ConnectTimeout=5"

# Pull current FS fleet from postgres (control-plane truth).
DB_HOST="${DATABASE_URL##*@}"
DB_HOST="${DB_HOST%/*}"
DB_HOST="${DB_HOST%:*}"
FS_IPS=$(PGPASSWORD="${DATABASE_URL#*:}" PGPASSWORD="$(echo "$DATABASE_URL" | sed -E 's|postgres://[^:]+:([^@]+)@.*|\1|')" \
  psql "$DATABASE_URL" -At -c \
  "SELECT public_ip FROM media_nodes WHERE service_type='freeswitch' AND state IN ('active','provisioning') ORDER BY hetzner_id;")

[ -z "$FS_IPS" ] && { echo "[kamailio-bootstrap] no freeswitch nodes in DB; aborting"; exit 1; }

# Build dispatcher.list
DISP_TMP="$(mktemp /tmp/disp.XXXXXX.list)"
{
  echo "# setid destination flags"
  while IFS= read -r ip; do
    [ -z "$ip" ] && continue
    echo "1 sip:$ip:5080"
  done <<< "$FS_IPS"
} > "$DISP_TMP"

# Build kamailio.cfg
CFG_TMP="$(mktemp /tmp/kam.XXXXXX.cfg)"
cat > "$CFG_TMP" <<CFG
# Generated by kamailio-bootstrap.sh — do not edit on the box.
debug=2
log_stderror=no
log_facility=LOG_LOCAL0
fork=yes
children=4
auto_aliases=yes

listen=udp:0.0.0.0:5060 advertise $FIP:5060
listen=tcp:0.0.0.0:5060 advertise $FIP:5060

loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "rr.so"
loadmodule "pv.so"
loadmodule "maxfwd.so"
loadmodule "usrloc.so"
loadmodule "registrar.so"
loadmodule "textops.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "ctl.so"
loadmodule "cfg_rpc.so"
loadmodule "kex.so"
loadmodule "corex.so"
loadmodule "dispatcher.so"
loadmodule "pike.so"
loadmodule "htable.so"

modparam("usrloc", "db_mode", 0)
modparam("registrar", "method_filtering", 1)
modparam("dispatcher", "list_file", "/etc/kamailio/dispatcher.list")
modparam("dispatcher", "ds_ping_method", "OPTIONS")
modparam("dispatcher", "ds_probing_threshold", 3)

# pike anti-flood: >100 req/s for >2s ⇒ block source for 5s
modparam("pike", "sampling_time_unit", 2)
modparam("pike", "reqs_density_per_unit", 100)
modparam("pike", "remove_latency", 5)

request_route {
  if (!pike_check_req()) { xlog("L_ALERT","pike: blocked \$si\\n"); exit; }
  if (!mf_process_maxfwd_header("10")) { sl_send_reply("483","Too Many Hops"); exit; }
  if (!sanity_check("17895", "7")) { xlog("L_WARN","sanity check failed\\n"); exit; }

  if (is_method("REGISTER")) {
    if (!save("location")) { sl_reply_error(); }
    exit;
  }

  if (is_method("INVITE")) {
    record_route();
    if (!ds_select_dst("1", "4")) {
      sl_send_reply("503","No available destinations");
      exit;
    }
    t_on_failure("RTF_DISPATCHER");
  }

  if (loose_route()) { route(RELAY); exit; }

  if (!t_relay()) sl_reply_error();
}

route[RELAY] { if (!t_relay()) sl_reply_error(); exit; }

failure_route[RTF_DISPATCHER] {
  if (t_is_canceled()) exit;
  if (t_check_status("(408|5[0-9][0-9])")) {
    if (ds_next_dst()) { t_on_failure("RTF_DISPATCHER"); t_relay(); exit; }
  }
}
CFG

# Push to box and restart
scp $SSH_OPTS "$CFG_TMP"  root@"$SIP_IP":/etc/kamailio/kamailio.cfg >/dev/null
scp $SSH_OPTS "$DISP_TMP" root@"$SIP_IP":/etc/kamailio/dispatcher.list >/dev/null
rm -f "$CFG_TMP" "$DISP_TMP"

ssh $SSH_OPTS root@"$SIP_IP" "kamailio -c -f /etc/kamailio/kamailio.cfg >/dev/null && systemctl restart kamailio && sleep 1 && systemctl is-active kamailio"

echo "[kamailio-bootstrap] $SIP_IP — config + dispatcher applied (FS targets: $(echo "$FS_IPS" | wc -l))"
