#!/bin/bash
# Kamailio role bootstrap — applies the canonical sip_proxy config to a new
# fleet sip_proxy node. Idempotent. Run from ctl02 over SSH.
#
# Usage:  kamailio-bootstrap.sh <sip-node-public-ip> <floating-ip>
#
# What it does:
#   1. Write the canonical kamailio.cfg with REGISTRAR + DISPATCHER, FIP advertise,
#      pike anti-flood module loaded.
#   2. Generate dispatcher.list pointing at the active freeswitch fleet (port 5080
#      — the external profile, no auth, ACL-gated by source IP).
#   3. Restart kamailio.
#
# When the FS fleet changes, re-run this script per sip_proxy node so the
# dispatcher list stays current. (A control-plane watcher could automate this.)

set -euo pipefail

SIP_IP="${1:-}"
FIP="${2:-}"
[ -z "$SIP_IP" ] || [ -z "$FIP" ] && { echo "usage: $0 <sip-node-ip> <floating-ip>"; exit 1; }

[ -f /opt/tpbx/.env ] && set -a && . /opt/tpbx/.env && set +a
SSH_KEY="${SSH_PRIVATE_KEY_PATH:-/opt/tpbx/secrets/ssh_key}"
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ConnectTimeout=5"

# Pull current FS fleet from postgres (control-plane truth).
DB_HOST="${DATABASE_URL##*@}"
DB_HOST="${DB_HOST%/*}"
DB_HOST="${DB_HOST%:*}"
FS_IPS=$(psql "$DATABASE_URL" -At -c \
  "SELECT public_ip FROM media_nodes WHERE service_type='freeswitch' AND state IN ('active','provisioning') ORDER BY hetzner_id;")

[ -z "$FS_IPS" ] && { echo "[kamailio-bootstrap] no freeswitch nodes in DB; aborting"; exit 1; }

# Carrier ACL: only INVITEs from these source IPs may dispatch into the FS fleet.
# Pulled from carriers table (any carrier with direction in/both and status=active).
# Hosts are resolved to A records — if a carrier sends INVITEs from a different
# IP than its inbound host, set carriers.host to that signaling IP explicitly.
CARRIER_HOSTS=$(psql "$DATABASE_URL" -At -c \
  "SELECT host FROM carriers WHERE status='active' AND direction IN ('inbound','both');")
CARRIER_IPS=""
while IFS= read -r h; do
  [ -z "$h" ] && continue
  # Already an IPv4 literal? use as-is. Otherwise resolve.
  if [[ "$h" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then ips="$h"
  else ips=$(getent ahostsv4 "$h" 2>/dev/null | awk '{print $1}' | sort -u); fi
  for ip in $ips; do CARRIER_IPS+="$ip"$'\n'; done
done <<< "$CARRIER_HOSTS"
CARRIER_IPS=$(printf '%s' "$CARRIER_IPS" | sort -u | sed '/^$/d')

# Build two `if`-chain allowlists. Empty list ⇒ "0" so the branch never
# matches (kamailio falls through to the 403 default-deny).
#
# CARRIER_ACL — sources kamailio dispatches INWARD into the FS pool.
# FS_ACL      — internal FS sources whose INVITEs we forward OUTBOUND by
#               Request-URI. POSTROUTING SNAT (below) rewrites the source
#               IP to the FIP so the carrier sees a stable address even when
#               fs nodes are added/replaced.
build_acl() {
  local ips="$1" expr=""
  if [ -n "$ips" ]; then
    while IFS= read -r ip; do
      [ -z "$ip" ] && continue
      [ -n "$expr" ] && expr+=" || "
      expr+="\$si == \"$ip\""
    done <<< "$ips"
  else
    expr="0"
  fi
  printf '%s' "$expr"
}
CARRIER_ACL=$(build_acl "$CARRIER_IPS")
FS_ACL=$(build_acl "$FS_IPS")

# Build dispatcher.list
DISP_TMP="$(mktemp /tmp/disp.XXXXXX.list)"
{
  echo "# setid destination flags"
  while IFS= read -r ip; do
    [ -z "$ip" ] && continue
    echo "1 sip:$ip:5080"
  done <<< "$FS_IPS"
} > "$DISP_TMP"

# Build kamailio.cfg
CFG_TMP="$(mktemp /tmp/kam.XXXXXX.cfg)"
cat > "$CFG_TMP" <<CFG
# Generated by kamailio-bootstrap.sh — do not edit on the box.
debug=2
log_stderror=no
log_facility=LOG_LOCAL0
fork=yes
children=4
auto_aliases=yes

listen=udp:0.0.0.0:5060 advertise $FIP:5060
listen=tcp:0.0.0.0:5060 advertise $FIP:5060

loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "rr.so"
loadmodule "pv.so"
loadmodule "maxfwd.so"
loadmodule "usrloc.so"
loadmodule "registrar.so"
loadmodule "textops.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "ctl.so"
loadmodule "cfg_rpc.so"
loadmodule "kex.so"
loadmodule "corex.so"
loadmodule "dispatcher.so"
loadmodule "pike.so"
loadmodule "htable.so"

modparam("usrloc", "db_mode", 0)
modparam("registrar", "method_filtering", 1)
modparam("dispatcher", "list_file", "/etc/kamailio/dispatcher.list")
modparam("dispatcher", "ds_ping_method", "OPTIONS")
modparam("dispatcher", "ds_probing_threshold", 3)

# pike anti-flood: >100 req/s for >2s ⇒ block source for 5s
modparam("pike", "sampling_time_unit", 2)
modparam("pike", "reqs_density_per_unit", 100)
modparam("pike", "remove_latency", 5)

request_route {
  if (!pike_check_req()) { xlog("L_ALERT","pike: blocked \$si\\n"); exit; }
  if (!mf_process_maxfwd_header("10")) { sl_send_reply("483","Too Many Hops"); exit; }
  if (!sanity_check("17895", "7")) { xlog("L_WARN","sanity check failed\\n"); exit; }

  if (is_method("REGISTER")) {
    if (!save("location")) { sl_reply_error(); }
    exit;
  }

  if (is_method("INVITE")) {
    # Inbound from carrier → dispatch to FS pool. Carrier IPs come from the
    # carriers table at bootstrap time. Re-run kamailio-bootstrap (or POST
    # /platform/autoscaler/rebootstrap?serviceType=sip_proxy) after changing
    # carriers.
    if ($CARRIER_ACL) {
      record_route();
      if (!ds_select_dst("1", "4")) {
        sl_send_reply("503","No available destinations");
        exit;
      }
      t_on_failure("RTF_DISPATCHER");
    }
    # Outbound from internal FS → forward by Request-URI (carrier address).
    # POSTROUTING SNAT rewrites src → FIP so the carrier sees a stable
    # address regardless of which fs node sourced the call. FS IP list comes
    # from media_nodes (service_type='freeswitch'); also re-bootstrap when
    # the fs fleet changes.
    else if ($FS_ACL) {
      record_route();
    }
    else {
      xlog("L_NOTICE","[acl] reject INVITE from unauthorized source \$si\\n");
      sl_send_reply("403","Unauthorized source");
      exit;
    }
  }

  if (loose_route()) { route(RELAY); exit; }

  if (!t_relay()) sl_reply_error();
}

route[RELAY] { if (!t_relay()) sl_reply_error(); exit; }

failure_route[RTF_DISPATCHER] {
  if (t_is_canceled()) exit;
  if (t_check_status("(408|5[0-9][0-9])")) {
    if (ds_next_dst()) { t_on_failure("RTF_DISPATCHER"); t_relay(); exit; }
  }
}
CFG

# Push to box and restart
scp $SSH_OPTS "$CFG_TMP"  root@"$SIP_IP":/etc/kamailio/kamailio.cfg >/dev/null
scp $SSH_OPTS "$DISP_TMP" root@"$SIP_IP":/etc/kamailio/dispatcher.list >/dev/null
rm -f "$CFG_TMP" "$DISP_TMP"

ssh $SSH_OPTS root@"$SIP_IP" "kamailio -c -f /etc/kamailio/kamailio.cfg >/dev/null && systemctl restart kamailio && sleep 1 && systemctl is-active kamailio"

# SNAT outbound UDP/5060 to use the FIP as src. Without this, kamailio replies
# leak the underlying server's primary IP, which strict carriers reject as a
# Via/L4 mismatch. The FIP is the only IP the carrier knows about. Persisted
# via netfilter-persistent so it survives reboot.
ssh $SSH_OPTS root@"$SIP_IP" "
  set -e
  # Preseed debconf so iptables-persistent installs without prompting.
  echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
  echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections
  DEBIAN_FRONTEND=noninteractive apt-get install -y -q netfilter-persistent iptables-persistent >/dev/null 2>&1 || true
  iptables -t nat -C POSTROUTING -o eth0 -p udp --sport 5060 -j SNAT --to-source $FIP 2>/dev/null \
    || iptables -t nat -A POSTROUTING -o eth0 -p udp --sport 5060 -j SNAT --to-source $FIP
  mkdir -p /etc/iptables
  netfilter-persistent save >/dev/null 2>&1 || iptables-save > /etc/iptables/rules.v4
"

echo "[kamailio-bootstrap] $SIP_IP — config + dispatcher applied (FS targets/internal-ACL: $(echo "$FS_IPS" | sed '/^$/d' | wc -l), carrier ACL ips: $(echo "$CARRIER_IPS" | sed '/^$/d' | wc -l))"
