import type { Job } from 'bullmq';
import { eq } from 'drizzle-orm';
import { db } from '../db/client';
import { kbSources, kbChunks } from '../db/schema';
import { logger } from '../lib/logger';

interface KbIndexerJob {
  sourceId: string;
  voicebotConfigId: string;
  tenantId: string;
  sourceType: string;
  minioKey?: string;
  sourceUrl?: string;
  question?: string;
  answer?: string;
}

export async function processKbIndexer(job: Job<KbIndexerJob>) {
  const { sourceId, voicebotConfigId, tenantId, sourceType } = job.data;
  logger.info({ sourceId, sourceType }, 'Indexing KB source');

  await db.update(kbSources).set({ status: 'processing' }).where(eq(kbSources.id, sourceId));

  try {
    let chunks: string[] = [];

    if (sourceType === 'qa') {
      // Q&A pairs are single chunks
      chunks = [`Q: ${job.data.question}\nA: ${job.data.answer}`];
    } else if (sourceType === 'document') {
      // TODO: Download PDF from MinIO, extract text, split into chunks
      chunks = ['[Document chunk placeholder - PDF extraction pending]'];
    } else if (sourceType === 'url') {
      // TODO: Fetch URL, extract text, split into chunks
      chunks = ['[URL chunk placeholder - Web scraping pending]'];
    }

    // Insert chunks (embeddings to be generated by Ollama/OpenAI)
    for (let i = 0; i < chunks.length; i++) {
      await db.insert(kbChunks).values({
        tenantId,
        kbSourceId: sourceId,
        voicebotConfigId,
        content: chunks[i],
        chunkIndex: i,
        tokenCount: Math.ceil(chunks[i].length / 4), // rough estimate
        // embedding: null — filled by separate embedding job
      });
    }

    await db.update(kbSources).set({
      status: 'processed',
      chunkCount: chunks.length,
    }).where(eq(kbSources.id, sourceId));

    logger.info({ sourceId, chunks: chunks.length }, 'KB indexing complete');
  } catch (err) {
    await db.update(kbSources).set({ status: 'failed' }).where(eq(kbSources.id, sourceId));
    throw err;
  }
}
